development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://azbjqjwmfkwoac:3bdfdf1729dd9d5e0940d174f6b22b97ba20851bc45e9b41dff63ca5133deacc@ec2-107-22-168-211.compute-1.amazonaws.com:5432/d3a5crefj4utas
  channel_prefix: louisWebsite_production
